"""confirmed registration support

Revision ID: 87fc2bd47d8a
Revises: de7a2289faa7
Create Date: 2016-08-09 16:38:07.372145

"""

# revision identifiers, used by Alembic.
revision = '87fc2bd47d8a'
down_revision = 'de7a2289faa7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
